analyzer:
  errors:
    use_key_in_widget_constructors: false
    invalid_annotation_target: ignore
  exclude:
    - lib/app/utils/translations/generated/*.dart
    - lib/app/utils/translations/generated/intl/*.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/**/injectable.config.dart

linter:
  rules:
    - join_return_with_assignment
    - prefer_expression_function_bodies
    - sort_constructors_first
    - avoid_relative_lib_imports
    - avoid_unused_constructor_parameters
    - always_put_required_named_parameters_first
    - prefer_relative_imports
    - directives_ordering
    - prefer_single_quotes
