name: flutter_recruitment_task
description: Flutter recruitment task.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.8.1
  http: 1.2.1
  auto_route: ^8.0.3
  freezed: ^2.5.2
  retrofit: ^4.1.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  package_info_plus: ^7.0.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  json_serializable: 6.7.1
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
